
version: '3.7'

services:

  ##zookeeper config

 zookeeper:
  image: wurstmeister/zookeeper
  container_name: zookeeper
  ports:
    - "2181:2181"

##kafka config

 kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

##akhq config

 akhq:
      # build:
      #   context: .
      image: tchiotludo/akhq
      environment:
        AKHQ_CONFIGURATION: |
         akhq:
            connections:
              docker-kafka-server:
                properties:
                  bootstrap.servers: "kafka:9092"
                schema-registry:
                  url: "http://schema-registry:8085"
                connect:
                  - name: "connect"
                    url: "http://connect:8083"

      ports:
        - "8080:8080"
